type: google.api.Service
config_version: 3
name: "*.apigateway.shinonome-375705.cloud.goog"
title: API Gateway + Cloud Run gRPC
apis:
- name: weather.v1.WeatherService
- name: greet.v1.GreetService
usage:
  rules:
  - selector: weather.v1.WeatherService.Weather
    allow_unregistered_calls: true
  - selector: greet.v1.GreetService.Greet
    allow_unregistered_calls: true
backend:
  rules:
  - selector: weather.v1.WeatherService.Weather
    address: grpcs://go-connect-weather-zugntxuibq-an.a.run.app
  - selector: greet.v1.GreetService.Greet
    address: grpcs://go-connect-greet-zugntxuibq-an.a.run.app
